'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function page(){const els=new Map();const el=id=>{if(!els.has(id))els.set(id,{value:'',textContent:'',hidden:false,disabled:false,children:[],replaceChildren(){this.children=[]},appendChild(c){this.children.push(c)},append(...c){this.children.push(...c)}});return els.get(id)};const ctx=vm.createContext({console,Map,Date,Number,String,JSON,Error,Promise,Uint8Array,atob,Blob,URL,crypto:{randomUUID:()=> 'request-000001'},document:{getElementById:el,createElement:tag=>({tag,textContent:'',children:[],append(...c){this.children.push(...c)},appendChild(c){this.children.push(c)},addEventListener(){},setAttribute(){}})},$:el,PIN:'SESSION-test',ROLES:['OFFICE'],show:id=>ctx.screen=id,toast:m=>ctx.message=m,api:async()=>({documents:[],nextCursor:null,summary:{count:0}})});vm.runInContext(fs.readFileSync('screens/biuro.js','utf8'),ctx);return {ctx,el,run:s=>vm.runInContext(s,ctx)};}
test('Biuro odmawia lokalnie bez OFFICE',async()=>{const p=page();p.ctx.ROLES=[];await p.run('openOffice()');assert.equal(p.ctx.screen,undefined);});
test('odpowiedź poprzedniej sesji nie wyświetla dokumentów',async()=>{const p=page();let resolve;p.ctx.api=()=>new Promise(r=>resolve=r);const pending=p.run('loadOfficeDocs()');p.ctx.PIN='NEW';resolve({documents:[{id:'secret',partner:'tajne'}],nextCursor:null,summary:{count:1}});await pending;assert.equal(p.el('officeList').children.length,0);});
test('ceny z groszy odróżniają brak od zera',()=>{const p=page();assert.equal(p.run('officePriceText(null)'),'—');assert.equal(p.run('officePriceText(0)'),'0,00');assert.equal(p.run('officePriceText(123)'),'1,23');});

test('formularz cen używa części HTML okna, zapis zamyka okno',async()=>{const p=page();let args;p.ctx.sheet=(...a)=>args=a;p.ctx.hideSheet=()=>p.ctx.closed=true;p.ctx.isNet=()=>false;p.run("OFFICE_DETAIL={document:{id:'D1'},rows:[{sku:'A',name:'Produkt',qty:1,buyCents:null,sellCents:null,revision:0}],totals:{}};editOfficePrice('A')");assert.equal(args[1],'');assert.match(args[3],/id="officeBuy"/);p.el('officeBuy').value='80';p.el('officeSell').value='100';p.ctx.api=async()=>({row:{buyCents:8000,sellCents:10000,revision:1},totals:{buyCents:8000,sellCents:10000,profitCents:2000,margin:20,markup:25,incomplete:false}});await p.run("saveOfficePrice('A')");assert.equal(p.ctx.closed,true);assert.equal(p.run('OFFICE_DETAIL.rows[0].revision'),1);});
test('stara sesja nie pobiera eksportu',async()=>{const p=page();let resolve;p.run("OFFICE_DETAIL={document:{id:'D1'},rows:[],totals:{}}");p.ctx.api=()=>new Promise(r=>resolve=r);const pending=p.run("downloadOfficeDocument('D1','xlsx')");p.ctx.PIN='NEW';resolve({filename:'secret.xlsx',mime:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',base64:'UEsDBA=='});await pending;assert.equal(p.el('officeDocMessage').textContent,'Przygotowuję plik…');});
test('błąd zapisu pozostawia wprowadzone wartości',async()=>{const p=page();p.ctx.isNet=()=>true;p.run("OFFICE_DETAIL={document:{id:'D1'},rows:[{sku:'A',revision:0}],totals:{}}");p.el('officeBuy').value='80,25';p.el('officeSell').value='100';p.ctx.api=async()=>{throw Error('Sieć niedostępna')};await p.run("saveOfficePrice('A')");assert.equal(p.el('officeBuy').value,'80,25');assert.equal(p.el('officeSaveMessage').textContent,'Sieć niedostępna');});
