'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function page(){const els=new Map(),storage=new Map();const el=id=>{if(!els.has(id))els.set(id,{value:'',textContent:'',children:[],classList:{add(){},remove(){}},addEventListener(){},appendChild(c){this.children.push(c)},set innerHTML(v){this.children=[];this.html=v}});return els.get(id)};
const ctx=vm.createContext({Map,Set,Date,JSON,Number,String,Promise,Error,console,setTimeout(){},clearTimeout(){},document:{getElementById:el,createElement:()=>({}),querySelectorAll:()=>[],addEventListener(){}},window:{addEventListener(){}},navigator:{},WarehouseScanner:{Scanner:class{stop(){}}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)}});
const script=[...fs.readFileSync('index.html','utf8').matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]).join('\n');vm.runInContext(script.slice(0,script.lastIndexOf('(function init(){')),ctx);vm.runInContext(fs.readFileSync('screens/produkty.js','utf8'),ctx);vm.runInContext("PIN='SESSION-old';USER_ID='EMP-test';DOC={id:'D1'};show=id=>{screen=id};stopScanner=()=>{};refreshItems=()=>{};resetScan=()=>{};enqueue=()=>{enqueued=true};",ctx);return {ctx,el,run:s=>vm.runInContext(s,ctx)};}
test('utrata odpowiedzi doliczenia nie dodaje drugi raz osobnej pozycji',async()=>{const h=page();h.ctx.apiStub=async()=>{throw Error('Failed to fetch')};h.run('api=apiStub');await h.run("mergeInto({clientId:'old',qty:2,name:'X',sku:'X'}, {clientId:'new',qty:3})");assert.equal(h.ctx.enqueued,undefined);assert.match(h.el('toast').textContent,/sprawdź|Sprawdź/);});
test('wylogowanie z nieważną sesją wysyła tylko jedno apiLogout',async()=>{const h=page();let count=0;h.ctx.fetch=async()=>{count++;if(count>3)throw Error('recursion');return {json:async()=>({ok:false,error:'AUTH'})}};h.run('logout()');await new Promise(r=>setImmediate(r));assert.equal(count,1);assert.equal(h.run('PIN'),null);});
test('błąd AUTH starej sesji nie wylogowuje nowej',async()=>{const h=page();let resolve;h.ctx.fetch=()=>new Promise(r=>{resolve=r});const pending=h.run("api('apiListProducts',PIN)");h.run("PIN='SESSION-new'");resolve({json:async()=>({ok:false,error:'AUTH'})});await assert.rejects(()=>pending,/AUTH/);assert.equal(h.run('PIN'),'SESSION-new');});
test('opóźniona karta produktu po wylogowaniu nie otwiera ekranu',async()=>{const h=page();let resolve;h.ctx.apiStub=()=>new Promise(r=>{resolve=r});h.run('api=apiStub');const pending=h.run("openProduct('X')");h.run("PIN=null;screen='scrLogin'");resolve({product:{sku:'X',name:'tajne'},moves:[],history:[]});await pending;assert.equal(h.ctx.screen,'scrLogin');assert.equal(h.el('productTitle').textContent,'');});
test('starsze wyszukiwanie nie nadpisuje nowego filtra',async()=>{const h=page();const resolves=[];h.ctx.apiStub=()=>new Promise(r=>resolves.push(r));h.run('api=apiStub');const first=h.run('openProducts()'),second=h.run('openProducts()');resolves[1]([{sku:'NEW',name:'Nowy',qty:1}]);await second;resolves[0]([{sku:'OLD',name:'Stary',qty:1}]);await first;assert.ok(h.el('productList').children.every(c=>!String(c.textContent).includes('OLD')));});
test('spóźniony sukces API poprzedniej sesji nie wraca do aplikacji',async()=>{const h=page();let resolve;h.ctx.fetch=()=>new Promise(r=>{resolve=r});const pending=h.run("api('apiStartDoc',PIN,'EXPORT','Klient')");h.run("PIN='SESSION-new'");resolve({json:async()=>({ok:true,data:{id:'old-doc',status:'OTWARTA'}})});await assert.rejects(()=>pending,/Sesja zmieniona/);assert.equal(h.run('PIN'),'SESSION-new');});
test('odpowiedź logowania po wylogowaniu nie przywraca sesji',async()=>{const h=page();let resolve;h.ctx.apiStub=(fn)=>fn==='apiLogin'?new Promise(r=>{resolve=r}):Promise.resolve({ok:true});h.run('api=apiStub;afterLogin=()=>{}');const pending=h.run("login('12345678')");h.run('logout()');resolve({token:'SESSION-delayed',id:'EMP-test',name:'Tester',roles:[]});await pending;assert.equal(h.run('PIN'),null);});
test('PIN logowania i potwierdzenia nie pozostają w formularzach po użyciu',async()=>{const h=page();h.ctx.apiStub=async()=>({token:'SESSION-current',id:'EMP-test',name:'Tester',roles:[]});h.run('api=apiStub;afterLogin=()=>{}');h.el('pinInput').value='12345678';await h.run("login('12345678')");assert.equal(h.el('pinInput').value,'');h.el('closePin').value='12345678';h.run('hideSheet()');assert.equal(h.el('closePin').value,'');h.el('pinInput').value='12345678';h.run('logout()');assert.equal(h.el('pinInput').value,'');});

test('edycja ilości odrzuca ułamek i przyjmuje zero inwentaryzacji',async()=>{const h=page();let actions,updates=[];h.ctx.capture=(a)=>actions=a;h.ctx.apiStub=async(fn,...args)=>{updates.push(args);return {}};h.run("api=apiStub;sheet=(title,body,a)=>capture(a);DOC={id:'D1',type:'INWENTARYZACJA'};myItems=[{clientId:'I1',qty:2,name:'X',sku:'X'}];itemMenu('I1')");actions[0].fn();h.el('newQty').value='1.5';await actions[0].fn();assert.equal(updates.length,0);h.el('newQty').value='0';await actions[0].fn();assert.equal(updates[0][3].qty,0);});
test('odpowiedź statusu po wyjściu nie przywraca dokumentu',async()=>{const h=page();let resolve;h.ctx.apiStub=()=>new Promise(r=>resolve=r);h.run('api=apiStub');const pending=h.run('refreshStatus()');h.run('DOC=null');resolve({id:'D1',status:'OTWARTA',participants:[]});await pending;assert.equal(h.run('DOC'),null);});
test('starsza lista dostaw nie zastępuje eksportów',async()=>{const h=page();const rs=[];h.ctx.apiStub=()=>new Promise(r=>rs.push(r));h.run("api=apiStub;DOC_TYPE='DOSTAWA'");const a=h.run('loadDocs()');h.run("DOC_TYPE='EXPORT'");const b=h.run('loadDocs()');rs[1]([]);await b;const current=h.el('docsList').html;rs[0]([{id:'old',partner:'Old',date:'',participants:[]}]);await a;assert.equal(h.el('docsList').html,current);});
test('cena poprzedniego produktu nie nadpisuje nowego',async()=>{const h=page();let resolve;h.ctx.apiStub=()=>new Promise(r=>resolve=r);h.run("api=apiStub;cur={sku:'A',name:'A'}");const pending=h.run('showPrice()');h.run("cur={sku:'B',name:'B'}");h.el('prVal').textContent='nowy';resolve({hurt:12,detal:'',source:'IMPORT'});await pending;assert.equal(h.el('prVal').textContent,'nowy');});

test('wylogowanie resetuje filtry współdzielonego telefonu',()=>{const h=page();h.run("let DUNSKA_TAB='braki';api=async()=>({})");h.el('productQuery').value='A';h.el('productFilter').value='zero';h.run('logout()');assert.equal(h.run('DUNSKA_TAB'),'odbior');assert.equal(h.el('productQuery').value,'');assert.equal(h.el('productFilter').value,'all');});
test('zamknięcie bez FORCE_CLOSE nie oferuje wymuszenia',async()=>{const h=page();let actions;h.ctx.capture=a=>actions=a;h.ctx.apiStub=async()=>({needsForce:true,pending:['A']});h.run("api=apiStub;ROLES=['POST_STOCK'];sheet=(t,b,a)=>capture(a)");await h.run("doClose(false,'12345678')");assert.equal(actions.some(a=>a.label==='Zamknij mimo to'),false);});

test('zapis kartoteki odświeża katalog skanera i nie wysyła równolegle drugi raz',async()=>{const h=page();let resolve,calls=0,loads=0;h.ctx.apiStub=()=>{calls++;return new Promise(r=>resolve=r)};h.ctx.loadStub=async()=>loads++;h.run("api=apiStub;loadCatalog=loadStub;openProduct=async()=>{};ROLES=['PRODUCTS_EDIT'];PRODUCT_ORIGINAL='X'");h.el('productSku').value='X';h.el('productName').value='Nowy';const a=h.run('saveProduct()'),b=h.run('saveProduct()');assert.equal(calls,1);resolve({});await Promise.all([a,b]);assert.equal(loads,1);});
