const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function setup(saved){
 const storage=new Map(saved?[['mg_docjson',JSON.stringify(saved)],['queue','nietknięta']]:[]),els=new Map();
 const el=id=>{if(!els.has(id))els.set(id,{value:'',textContent:'',children:[],classList:{add(){},remove(){}},addEventListener(){},appendChild(b){this.children.push(b)},set innerHTML(v){this.children=[]}});return els.get(id)};
 const ctx=vm.createContext({Map,Set,Date,JSON,Number,String,Promise,Error,console,setTimeout(){},clearTimeout(){},document:{getElementById:el,createElement:()=>({}),querySelectorAll:()=>[],addEventListener(){}},window:{addEventListener(){}},navigator:{},WarehouseScanner:{Scanner:class{}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)}});
 const script=[...fs.readFileSync('index.html','utf8').matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]).join('\n');vm.runInContext(script.slice(0,script.lastIndexOf('(function init(){')),ctx);
 ctx.info=saved;ctx.calls=[];ctx.apiStub=async(fn)=>{ctx.calls.push(fn);return fn==='apiRecentPartners'?['=SUM(1,2)','<img onerror=x>']:ctx.info};
 vm.runInContext("PIN='test';ME='Tester';api=apiStub;show=id=>{screen=id};loadCatalog=()=>{};processQueue=()=>{};enterDoc=d=>{screen=d.status==='OTWARTA'?'scrCount':'scrHome'}",ctx);
 return {ctx,storage,el,run:s=>vm.runInContext(s,ctx)};
}
for(const offline of [false,true]) test('wznowienie wymaga wyboru, offline='+offline,async()=>{
 const h=setup({id:'D1',title:'EXPORT do Klienta',status:'OTWARTA'});await h.run(`afterLogin(${offline})`);assert.equal(h.ctx.screen,'scrHome');assert.match(h.el('shTitle').textContent,/EXPORT do Klienta/);
 assert.deepEqual(h.el('shActions').children.map(b=>b.textContent),['Wróć','Nie teraz']);h.el('shActions').children[0].onclick();await new Promise(resolve=>setImmediate(resolve));assert.equal(h.ctx.screen,'scrCount');assert.equal(h.ctx.calls.filter(f=>f==='apiDocInfo').length,offline?0:2);
});
test('Nie teraz czyści tylko zapis dokumentu',async()=>{const h=setup({id:'D1',status:'OTWARTA'});await h.run('afterLogin()');h.el('shActions').children[1].onclick();assert.equal(h.ctx.screen,'scrHome');assert.equal(h.storage.has('mg_docjson'),false);assert.equal(h.storage.get('queue'),'nietknięta')});
for(const saved of [null,{id:'D1',status:'ZAMKNIĘTA'}]) test('brak okna bez otwartego dokumentu '+JSON.stringify(saved),async()=>{const h=setup(saved);await h.run('afterLogin()');assert.equal(h.ctx.screen,'scrHome');assert.equal(h.el('shActions').children.length,0)});
test('awaria sieci pozwala wrócić do zapisanego dokumentu',async()=>{const h=setup({id:'D1',status:'OTWARTA'});h.ctx.apiStub=async()=>{throw Error('offline')};h.run('api=apiStub');await h.run('afterLogin()');assert.equal(h.ctx.screen,'scrHome');h.el('shActions').children[0].onclick();await new Promise(resolve=>setImmediate(resolve));assert.equal(h.ctx.screen,'scrCount')});
test('szybki wybór używa textContent i ustawia pole, dostawa bez Duńskiej',async()=>{const h=setup();h.run("DOC_TYPE='EXPORT'");await h.run('loadRecentPartners()');assert.deepEqual(h.el('recentPartners').children.map(b=>b.textContent),['Magazyn Duńska','=SUM(1,2)','<img onerror=x>']);h.el('recentPartners').children[2].onclick();assert.equal(h.el('newPartner').value,'<img onerror=x>');h.run("DOC_TYPE='DOSTAWA'");await h.run('loadRecentPartners()');assert.equal(h.el('recentPartners').children.length,2)});
test('dokument zamknięty przed kliknięciem nie otwiera liczenia',async()=>{const h=setup({id:'D1',status:'OTWARTA'});await h.run('afterLogin()');h.ctx.info={id:'D1',status:'ZAMKNIĘTA'};h.el('shActions').children[0].onclick();await new Promise(resolve=>setImmediate(resolve));assert.equal(h.ctx.screen,'scrHome')});
test('odpowiedź starej sesji nie pokazuje okna i nie czyści nowego zapisu',async()=>{const h=setup({id:'D1',status:'OTWARTA'});let resolve;h.ctx.apiStub=()=>new Promise(r=>{resolve=r});h.run('api=apiStub');const pending=h.run('afterLogin()');h.run("PIN='nowy'");h.storage.set('mg_docjson','nowy zapis');resolve(h.ctx.info);await pending;assert.equal(h.el('shActions').children.length,0);assert.equal(h.storage.get('mg_docjson'),'nowy zapis')});
