'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function fixture(){let uuid=0;const els=new Map(),el=id=>{if(!els.has(id))els.set(id,{value:'',textContent:'',hidden:false,disabled:false,children:[],replaceChildren(){this.children=[]},append(...x){this.children.push(...x)},appendChild(x){this.children.push(x)}});return els.get(id);};const element=tag=>({tag,textContent:'',children:[],append(...x){this.children.push(...x)},appendChild(x){this.children.push(x)},addEventListener(){},setAttribute(){},click(){}});const ctx=vm.createContext({console,Map,Date,String,Number,JSON,Error,Promise,crypto:{randomUUID:()=> 'order-request-'+(++uuid)},document:{getElementById:el,createElement:element},$:el,PIN:'session',ROLES:['OFFICE'],officeAllowed:()=>ctx.ROLES.includes('OFFICE'),officeText:(tag,text)=>Object.assign(element(tag),{textContent:text}),officePriceText:x=>x===null?'—':(x/100).toFixed(2),show:s=>ctx.screen=s,toast:s=>ctx.message=s,api:async()=>({products:[],total:0,nextCursor:null}),sheet:(...args)=>ctx.modal=args,hideSheet:()=>{},isNet:()=>true});vm.runInContext(fs.readFileSync('screens/zamowienia.js','utf8'),ctx);return {ctx,el,run:s=>vm.runInContext(s,ctx)};}
test('oba rodzaje i powtórny SKU zwiększają ilość, usunięcie działa',()=>{const p=fixture();p.run("newOfficeOrder('KLIENT');addOfficeOrderItem({sku:'A',ean:'001',name:'=Towar'});addOfficeOrderItem({sku:'A',ean:'001',name:'=Towar'})");assert.equal(p.run('ORDER_DRAFT.items.length'),1);assert.equal(p.run('ORDER_DRAFT.items[0].qty'),2);p.run("removeOfficeOrderItem('A')");assert.equal(p.run('ORDER_DRAFT.items.length'),0);p.run("newOfficeOrder('ZAKUP')");assert.equal(p.run('ORDER_DRAFT.kind'),'ZAKUP');});
test('stara sesja nie pokazuje katalogu ani zamówienia',async()=>{const p=fixture();let resolve;p.ctx.api=()=>new Promise(r=>resolve=r);p.run("newOfficeOrder('KLIENT')");const task=p.run('loadOfficeOrderCatalog()');p.ctx.PIN='new';resolve({products:[{sku:'SECRET',name:'Sekret'}],total:1,nextCursor:null});await task;assert.equal(p.el('orderCatalog').children.length,0);});
test('błąd sieci zachowuje formularz i requestId ponowienia',async()=>{const p=fixture(),requests=[];p.run("newOfficeOrder('KLIENT');addOfficeOrderItem({sku:'A',name:'Towar',ean:'001'})");p.el('orderPartner').value='Klient';p.ctx.api=async(fn,...args)=>{requests.push(args[1]);throw Error('Sieć niedostępna')};await p.run("saveOfficeOrder('SZKIC')");await p.run("saveOfficeOrder('SZKIC')");assert.equal(p.el('orderPartner').value,'Klient');assert.equal(requests[0].requestId,requests[1].requestId);assert.equal(p.run('ORDER_DRAFT.items.length'),1);assert.match(p.el('orderMessage').textContent,/Sieć/);});
test('reset usuwa poufne zamówienie i formularze, rola blokuje wejście',()=>{const p=fixture();p.run("newOfficeOrder('KLIENT');addOfficeOrderItem({sku:'A',name:'Poufne'})");p.el('orderPartner').value='Poufny klient';p.run('resetOrderSession()');assert.equal(p.run('ORDER_DRAFT'),null);assert.equal(p.el('orderPartner').value,'');assert.equal(p.el('orderItems').children.length,0);p.ctx.ROLES=[];p.run("newOfficeOrder('KLIENT')");assert.equal(p.run('ORDER_DRAFT'),null);});
test('eksport i druk starej sesji nie pobiera ani nie pokazuje pliku',async()=>{for(const call of ["downloadOfficeOrder('pdf')",'printOfficeOrder()']){const p=fixture();p.run("newOfficeOrder('KLIENT');ORDER_DRAFT.id='Z1'");let resolve;p.ctx.api=()=>new Promise(r=>resolve=r);const task=p.run(call);p.ctx.PIN='new';resolve({order:{id:'SECRET',items:[]},mime:'application/pdf',base64:'JVBERg=='});await task;assert.equal(p.el('officePrint').children.length,0);}});

test('konflikt zachowuje ceny i wymaga odświeżenia',async()=>{const p=fixture();p.run("newOfficeOrder('KLIENT');addOfficeOrderItem({sku:'A',name:'Towar'});ORDER_DRAFT.items[0].price='12.34'");p.el('orderPartner').value='Klient';p.ctx.api=async()=>{throw Error('REVISION_CONFLICT')};await p.run("saveOfficeOrder('SZKIC')");assert.equal(p.run('ORDER_DRAFT.items[0].price'),'12.34');assert.match(p.el('orderMessage').textContent,/Odśwież/);assert.equal(p.el('orderFormBody').disabled,false);});
test('spóźniony odczyt innego dokumentu nie nadpisuje bieżącego',async()=>{const p=fixture(),pending=[];p.ctx.api=()=>new Promise(resolve=>pending.push(resolve));const first=p.run("openOfficeOrder('OLD')"),second=p.run("openOfficeOrder('NEW')");pending[1]({order:{id:'NEW',kind:'KLIENT',status:'SZKIC',items:[]},history:[]});await second;pending[0]({order:{id:'OLD',kind:'KLIENT',status:'SZKIC',items:[]},history:[]});await first;assert.equal(p.run('ORDER_DRAFT.id'),'NEW');});

test('awaria serwera po zapisie zachowuje requestId do odzyskania bez duplikatu',async()=>{const p=fixture(),requests=[];p.run("newOfficeOrder('KLIENT')");p.ctx.isNet=()=>false;p.ctx.api=async(fn,...args)=>{requests.push(args[1]);throw Error('AWARIA HISTORII')};await p.run("saveOfficeOrder('SZKIC')");await p.run("saveOfficeOrder('SZKIC')");assert.equal(requests[0].requestId,requests[1].requestId);});
